### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by dmushkov** [vlingo/vlingo-xoom-starter#1]
try running on MacOS

first issue 
./xoom
bash: ./xoom: /bin/bash^M: bad interpreter: No such file or directory

explanation is here 
The ^M is a carriage return character. Linux uses the line feed character to mark the end of a line, whereas Windows uses the two-character sequence CR LF. Your file has Windows line endings, which is confusing Linux.

after fixing this 

second issue
bash-3.2$ ./xoom
Error: Unable to access jarfile /xxx/starter/bin/vlingo-xoom-starter-dist.jar

in bin directory is only vlingo-xoom-starter-1.3.0.jar

**Comment by danilo-ambrosio** [comment]
Thanks for sharing the details @dmushkov 
I'm gonna fix it ASAP.

**Comment by danilo-ambrosio** [comment]
@dmushkov 
I've made a few changes and already pushed it into master. We've successfully tested on Linux and Mac OS.
Could you please also validate it and let me know if it's working now?
Thanks!

**Comment by dmushkov** [comment]
it's fixed! Thanks
