### ISSUE TITLE
Retrieving an existing actor

### ISSUE THREAD

**Issue by Florian122** [vlingo/vlingo-xoom-starter#10]
Hello,

when I want to add a `Stock` to an existing `Portfolio` I need to call the `acquireStock` method.
In the `defineWith` method we create a new actor, but how do I retrieve the actor in the `acquireStock` method?
I tried to create an `Address` object with the same information as the one in the `defineWith` method but it didn't work.

See the [code](https://github.com/whzinformatik/stocktrader/blob/portfolio-stock-acquired/portfolio/src/main/java/com/whz/portfolio/model/portfolio/Portfolio.java) for reference.

```
static Completes<PortfolioState> defineWith(final Stage stage, final String owner) {
    final Address address = stage.world().addressFactory().uniquePrefixedWith("-p");
    final Portfolio portfolio = stage.actorFor(Portfolio.class, Definition.has(PortfolioEntity.class, Definition.parameters(address.idString())), address);
    return portfolio.portfolioCreated(owner);
}
```
```
static Completes<PortfolioState> acquireStock(final Stage stage, final String id, final String symbol, final int amount) {
    final Address address = stage.world().addressFactory().from("-p" + id);
    return stage.actorOf(PortfolioEntity.class, address).andThen((portfolio) -> portfolio.stockAcquired(symbol, amount)).andFinally();
}
```

**Comment by VaughnVernon** [comment]
@Florian122 See:

https://github.com/vlingo/vlingo-helloworld/blob/849a1ab5e64e55ccb8fad1d8af3ad972e22c05b1/src/main/java/io/vlingo/hello/resource/GreetingResource.java#L45

https://github.com/vlingo/vlingo-helloworld/blob/849a1ab5e64e55ccb8fad1d8af3ad972e22c05b1/src/main/java/io/vlingo/hello/resource/GreetingResource.java#L94

**Comment by Florian122** [comment]
Thank you for the help!

We had to change the implementation of the `AddressFactory` from `GridAddressFactory` to `BasicAddressFactory` because there was an error with the creation of the UUID for the id **_16_**.
Now it's working fine.

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr In order to use `GridAddressFactory` you must start the `Grid`.

I think what has happened is that you have some sort of hybrid between a Starter project and a manually programmed project. For example, if you were using auto-dispatch resources you wouldn't need to create an implementation, only an annotated interface.

https://docs.vlingo.io/vlingo-xoom/xoom-annotations
