### ISSUE TITLE
trying to download latest starter zipped distribution retrieves a snapshot version or an HTML file

### ISSUE THREAD

**Issue by razibus** [vlingo/vlingo-xoom-starter#13]
Following the documentation at https://docs.vlingo.io/vlingo-xoom/xoom-starter
`curl -L -O https://github.com/vlingo/vlingo-xoom-starter/raw/master/dist/starter.zip`
retrieves a SNAPSHOT one or an HTML file instead of a RELEASE version. 
I first got a SNAPSHOT version (1.4.1-SNAPSHOT) and now I get this: 
[starter.zip](https://github.com/vlingo/vlingo-xoom-starter/files/5816770/starter.zip)

For example:
```
$ curl -L -O https://github.com/vlingo/vlingo-xoom-starter/raw/master/dist/starter.zip
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                  Dload  Upload   Total   Spent    Left  Speed
100  172k  100  172k    0     0   356k      0 --:--:-- --:--:-- --:--:--  356k
```

**Comment by Florian-Schoenherr** [comment]
@razibus The latest available is a SNAPSHOT version, but is stable.
I updated the [docs](https://docs.vlingo.io/vlingo-xoom/xoom-starter) immediately, the links were old.
We have Github releases now, so you can use:
`curl -L -O https://github.com/vlingo/vlingo-xoom-starter/releases/latest/download/starter.zip`
Sorry for the inconvenience.

@VaughnVernon we could also release 1.4.4, so people know it is stable @danilo-ambrosio

**Comment by VaughnVernon** [comment]
Thanks, @Florian-Schoenherr We can do. I was waiting for completion on 1.5.0 features but I can release 1.4.4 now.

Will the github file cache auto update on the release? Are the docs and README fully updated?

**Comment by Florian-Schoenherr** [comment]
@VaughnVernon file cache? - if you mean the release, no, but after you changed the version I can do a new 1.4.4 release. And we could build this into github actions later.

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr Ok, I will release now. Yes, we must have that auto copy into Github releases.

Are the docs fully updated? We need that in those in the 1.4.4 release.

**Comment by Florian-Schoenherr** [comment]
@VaughnVernon There wasn't much new docs-worthy functionality. So yes. Also your last commit was not necessary, the links are already under "Installation" (they were only missing in docs)

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr Thanks for the heads up. I didn't see the links. I deleted the redundant docs.

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr We have not seen a confirmation from @razibus but can you confirm that this is fixed and close the issue?
