### ISSUE TITLE
names of statically imported methods may conflict with business level code

### ISSUE THREAD

**Issue by razibus** [vlingo/vlingo-xoom-starter#15]
Context : a User business object has been defined in xoom gui code generator. Consequently, a UserResource class has been created by the framework. In this class the ResourceBuilder class is statically imported :
```
import static io.vlingo.http.resource.ResourceBuilder.*;
```
If some business methods are defined for the User class, whose name conflict with the ResourceBuilder methods, the compilation fails. 

For instance : 
```
  @Override
  public Resource<?> routes() {
     return resource("UserResource",
        post("/users")
            .body(UserData.class)
            .handle(this::create),
        put("/users/{id}/")
            .param(String.class)
            .body(UserData.class)
            .handle(this::modify),
        delete("/users/{id}/")
            .param(String.class)
            .param(UserData.class)
            .handle(this::delete),
        get("/users")
            .handle(this::users)
     );
  }
```
If a put, post, get or delete method are defined by the user in the xoom gui, those are defined as member methods in the UserResource (`this::delete`) and the compiler tries to use them. If they match, the local methods are used, which will cause bugs. If they do not match, the compiler does not try to use the ResourceBuilder's ones and fails. 
The solution is to use a normal non static import and to explicitly mention the ResourceBuilder when using one of its methods. 
```
  @Override
  public Resource<?> routes() {
     return resource("UserResource",
        ResourceBuilder.post("/users")
            .body(UserData.class)
            .handle(this::create),
        ResourceBuilder.put("/users/{id}/")
            .param(String.class)
            .body(UserData.class)
            .handle(this::modify),
        ResourceBuilder.delete("/users/{id}/")
            .param(String.class)
            .param(UserData.class)
            .handle(this::delete),
        ResourceBuilder.get("/users")
            .handle(this::users)
     );
  }
```

**Comment by Florian-Schoenherr** [comment]
Thank you! Didn't think of that.
Also looks terrible. Maybe the other way around? Or we could validate that people can't use http-method names (deleteUser would work, maybe even _delete).

**Comment by VaughnVernon** [comment]
The generated code should use the fully-qualified class name of the fluent API method names to avoid conflicts:

```
io.vlingo.http.resource.ResourceBuilder.patch(...)
io.vlingo.http.resource.ResourceBuilder.post(...)
io.vlingo.http.resource.ResourceBuilder.put(...)
```

**Comment by danilo-ambrosio** [comment]
I've picked the @VaughnVernon suggestion. The `Rest Resource` template has been updated by using `Resource Builder` methods qualified names, without imports.

Please @razibus download the [updated `starter` binaries](https://github.com/vlingo/vlingo-xoom-starter/releases/tag/1.4.1-SNAPSHOT) and let me know if my changes meet what we've discussed here.

Thanks.

**Comment by VaughnVernon** [comment]
@danilo-ambrosio I think this can be marked as fixed and close it even though we have not heard from @razibus to confirm the fix.
