### ISSUE TITLE
Request : Consider adding a serialization mecanism in the xoom gui

### ISSUE THREAD

**Issue by razibus** [vlingo/vlingo-xoom-starter#16]
During a modeling session the xoom gui modeler freezed to death. I had to kill its process. All the work done was lost. 
I submit a request to include a serialization mecanism to the xoom gui modeler so that it may be dismissed, killed, stopped and then relaunched without loosing the work done using a data deserialization process.

**Comment by Florian-Schoenherr** [comment]
I'm gonna add localstorage 👍

**Comment by VaughnVernon** [comment]
@razibus Can you explain the gestures that lead to the hang?

**Comment by razibus** [comment]
Logs did not give much insight as much as I remember. The application simply freezed.
I was working on a model with around ten aggregates. 
The gui complained a little on the url's of the controllers, it considers them as wrong sometimes because it seems to keep a state that is not updated when you modify another filed (like the http verb...). 
Other observations I made were that :

- the first page (package, name...) was loosing its data, I had to rewrite it many times
- the generate button did not enter its in enabled state and remained greyed, may be because of the aforementioned bug,
- the page validation works better with the arrow buttons at the bottom part of the page, clicking around may give some surprise (in the left menu) regarding to data validation

So nothing very clear I am afraid. Sorry

**Comment by VaughnVernon** [comment]
@razibus Thanks for explaining. No need to be sorry. It is I who must apologize. We should have done a better job of this. I do admit that it's a new set of features and also we converted the UI from Angular to Svelte, which possibly missed some details.

/cc @Florian-Schoenherr @danilo-ambrosio

**Comment by Florian-Schoenherr** [comment]
@razibus Thank you.
- it's losing data if something is missing or not valid
- the generate button is greyed when something's missing, so yes
- navigation is not different

Localstorage implementation is nearly done, but will only save a new aggregate if you press "Add" for now, is that okay? 😄

**Comment by razibus** [comment]
Thank you. It is a good news to know that this feature is almost ready. 

Storing state upon explicit button interaction, using a save or add button, has the drawback that user must click every once to save the current state. Using other internal events, like content change + focus lost, to trigger a local storage would be more user-friendly but would require more work to manage the storage automatically. 

Thus, first, keeping it simple for development is better and agile-compliant. The button is okay. 
Later you'll see if you'll want to make it more user-friendly. 
Thanks again.

**Comment by Florian-Schoenherr** [comment]
@razibus It works now (haven't found any bugs with the localstorage), only saves if you have added something new to the aggregate list.
The dialog needs some work, that's the main problem - keeping it open after refresh isn't as easy as I thought it would be, but I tagged it. Also we can make it so clicking on the '+'-Card just adds a new card and then there's only an edit-mode. Makes the logic easier.

**Comment by razibus** [comment]
You are very kind and work quick !
I prefer to follow the product normal release cycle. It is better for the development team and I can wait ! 
Thank you. I am impressed !

**Comment by Florian-Schoenherr** [comment]
@razibus it's called svelte 😉

**Comment by VaughnVernon** [comment]
Since @Florian-Schoenherr won't brag about himself, I will do it for him. He is an outstanding young developer and has a lot of great ideas. Fortunately for him, he been scored very highly as a university intern for us since August, through this past semester/term. Unfortunately for us, he now must return to his university studies/work. I only say "unfortunately for us" from the standpoint that we lose much of his great efforts, but we are all very happy to have helped him with school and we are also happy that he has priorities to finish his degree.

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr Can this be marked fixed and close?
