### ISSUE TITLE
Framework generated code and business code may conflict

### ISSUE THREAD

**Issue by razibus** [vlingo/vlingo-xoom-starter#17]
Context : a Building object has been defined in the gui. The code generator produced an interface Building with the following static method : 
```
  static Completes<BuildingState> create(final Stage stage, final String id, final String name, final String address) {
    final Address address = stage.world().addressFactory().uniquePrefixedWith("g-");
    final Building building = stage.actorFor(Building.class, Definition.has(BuildingEntity.class, Definition.parameters(address.idString())), address);
    return building.create(id, name, address);
  }
```
There is a name conflict between the framework code and the business code on the `address` field. A basic workaround in this case was to change the framework's address variable to _address. However, in general:

- no assumption should be made on the actual business code by the framework (it should be agnostic of the actual business' variables and methods' names and work despite of this),
- the framework code should be encapsulated so that it cannot interfere with the generated user code. 

In this case, this part should be completly encapsulated :
```
    final Address address = stage.world().addressFactory().uniquePrefixedWith("g-");
    final Building building = stage.actorFor(Building.class, Definition.has(BuildingEntity.class, Definition.parameters(address.idString())), address);
 ```

**Comment by VaughnVernon** [comment]
@razibus Thanks. In fact those changes are being made for the next release. (We ran into this with the domain model parameters.)

**Comment by razibus** [comment]
Great !

**Comment by danilo-ambrosio** [comment]
Thanks for sharing details and guidance @razibus!

I placed an underscore in front of every local variable in the domain model templates. Could you please download the update [binaries](https://github.com/vlingo/vlingo-xoom-starter/releases/tag/1.4.1-SNAPSHOT) and let me know if the problem was solved?

I'm grateful for your collaboration!

**Comment by VaughnVernon** [comment]
@danilo-ambrosio I think we have used this ourselves enough to close without @razibus testing and confirming.

**Comment by danilo-ambrosio** [comment]
Agree @VaughnVernon . I will close it. This fix has been used for a while and it's working fine.
