### ISSUE TITLE
Wrong type in restoreSnapshot in generated Entity

### ISSUE THREAD

**Issue by Boerrild** [vlingo/vlingo-xoom-starter#25]
The EventSourced entity generated by xoom starter attempts to override "restoreSnapshot", but the declared generic type is wrong. It is probably hardcoded by mistake to <AccountState>, but should be whatever state the entity use:

Example of a generated entity named JournalEntity with a state of type JournalState:

        public final class JournalEntity extends EventSourced implements Journal {
          private JournalState state;
        
          ...
        
          /*
           * Restores my initial state by means of {@code state}.
           *
           * @param snapshot the {@code JournalState} holding my state
           * @param currentVersion the int value of my current version; may be helpful in determining if snapshot is needed
           */
          @Override
          protected <AccountState> void restoreSnapshot(final JournalState snapshot, final int currentVersion) {
            // OVERRIDE FOR SNAPSHOT SUPPORT
            // See: https://docs.vlingo.io/vlingo-lattice/entity-cqrs#eventsourced
          }

**Comment by VaughnVernon** [comment]
@Boerrild Are you using SNAPSHOT level or 1.5.0 release? I think you must be using the SNAPSHOT, which is not considered official. Can you please try the released version? It will be missing some features but it should be stable.

**Comment by VaughnVernon** [comment]
@Boerrild Please pull clear your local cache (not sure how you are getting snapshots) and run the generation and build again. This one should be fixed.

**Comment by Boerrild** [comment]
I followed the Getting started guide and ran 
    
    curl -L -O https://github.com/vlingo/vlingo-xoom-starter/releases/latest/download/starter.tar

And extracted it. It apparently gives me 1.5.1-SNAPSHOT.

**Comment by VaughnVernon** [comment]
I think you should try in this order:

1. Re-generate your project using the snapshot as before and execute the mvnw (after changing perms; I am trying to fix that now); this should generate the correct code now using the new `vlingo-xoom...1.5.1-SNAPSHOT.jar`
2. `$ git pull on vlingo-xoom` (the actual location of the bug in a template file; see below link). 

https://github.com/vlingo/vlingo-xoom/commit/663a2476b6e0389d2f52c8352234225c5e38c24a

**Comment by VaughnVernon** [comment]
Fixed by https://github.com/vlingo/vlingo-xoom/commit/663a2476b6e0389d2f52c8352234225c5e38c24a

**Comment by VaughnVernon** [comment]
@Boerrild I have confirmed this fix on MBP + MacOS.
