### ISSUE TITLE
Improve Generation Output Directory

### ISSUE THREAD

**Issue by VaughnVernon** [vlingo/vlingo-xoom-starter#27]
The Generation page currently defaults the output path to `D:\...`, which is possibly valid only for a Windows based filesystem. It may not be valid at all since some Windows filesystems will not have a `D:` drive.

The Generation page should instead default the project generation directory to a value that represents the current user operating environment.

```
String generationPath = System.getProperty("user.home") + File.separator + basePackageName + generationCount;
````

The `basePackageName` is the `String` value that has been entered in the Context page. This implies that the `basePackageName` must be set prior to generation, and the `generationPath` must change when the `basePackageName` changes.

The `generationCount` suffix is initially the value `1`. Every generation performed following the first the `generationCount` is incremented by `1`, yielding `2`, `3`, `4`...

The increasing value of `generationCount` can be manually deleted by the user in order to overwrite the previous generation, if desired. Requiring user editing forces a clear and explicit user choice, not am implied determination by Starter that could be responsible for loss of work.

**Comment by danilo-ambrosio** [comment]
It has been implemented [here](https://github.com/vlingo/vlingo-xoom-starter/commit/c288d5f5b2b0c664121b1f92e2d0c483cc7032ed).
