### ISSUE TITLE
Starter UI for Value Objects: Edit and Scope

### ISSUE THREAD

**Issue by VaughnVernon** [vlingo/vlingo-xoom-starter#30]
- The Value Object combo prevents editing the Value Object fields. When clicking on the VO name, the state fields are not refreshed, so user can only edit the Aggregate state fields.

- The Value Objects created in the context of a given Aggregate are not available for other Aggregate.

- Questions? Ask @danilo-ambrosio

**Comment by Florian-Schoenherr** [comment]
Just going through the UI changes, btw @abdullahcalisir12 I will review only.
1. Why is that just a Button now?
![image](https://user-images.githubusercontent.com/65456722/110235270-6df69880-7f2f-11eb-8cf1-46d8dd04d45d.png)
2. As a user, I have no idea what all of this (and the Dialog when clicking `New`) means:
![image](https://user-images.githubusercontent.com/65456722/110235345-d2b1f300-7f2f-11eb-88c5-e9ef86d2a1ff.png)
3. 
> in the context of a given Aggregate are not available for other Aggregate

If they should be available to other Aggregates, imho they should not be defined inside the AggregateCard. If we for example have a different screen or Dialog for Value Objects, that would also make it clear to the user what the UI does (see 2.).

I know that right now it should just work for us, but if it's easier to reason about and therefore faster to code with a seperate Dialog/Page we should do it that way now, not later.

**Comment by abdullahcalisir12** [comment]
@Florian-Schoenherr 

1- I used SlideGroup, there was a bug SlideGroup wasn't calculating its width right so it was causing UI problem that's why I converted a button and removed it from the card list.

2- If you have any suggestions feel free to offer, I would like to change the UI.

3- available for other aggregates is solved

**Comment by Florian-Schoenherr** [comment]
@abdullahcalisir12 the suggestion was to put Value Objects in their own Dialog and just reference them in AggregateDialog 👍

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr @abdullahcalisir12 The separate dialog is ok but it must be a choice from inside the aggregate dialog because that's where you need the new types to use in an aggregate. Should NEW > be an option on the field type dropdown?

**Comment by abdullahcalisir12** [comment]
@Florian-Schoenherr @VaughnVernon 

@danilo-ambrosio provided me a json schema for valueObjects settings that's why I changed UI and implementation. You can review new UI here at #31

**Comment by VaughnVernon** [comment]
@abdullahcalisir12 Thanks. Could you please provide a few screen captures on the new features, how the dialog is reached and what it looks like? I won't have time for the next 5 hours to review.

**Comment by Florian-Schoenherr** [comment]
@VaughnVernon I would keep Dropdowns as a selection, "New" could be a button beside it.

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr @abdullahcalisir12 Yes, that's fine.

**Comment by VaughnVernon** [comment]
Done.
