### ISSUE TITLE
NullPointerException in Sourced

### ISSUE THREAD

**Issue by flaxel** [vlingo/vlingo-xoom-starter#4]
We found a little bug, if you create a project with the `vlingo_xoom_starter`. You get the following code in the `CommandModelJournalProvider` for the `FeedbackSubmittedEvent`:

```java
registry.register(
        new Info(
            journal, FeedbackSubmittedEvent.class, FeedbackSubmittedEvent.class.getSimpleName()));
```

To solve this bug, we have changed the lines as follows. This will register the actor instead of the event.

```java
registry.register(
        new Info(
            journal, FeedbackActor.class, FeedbackActor.class.getSimpleName()));
```

This implementation can be found in this [repository](https://github.com/whzinformatik/stocktrader).

**Comment by VaughnVernon** [comment]
@flaxel Thanks for reporting the issue.

@danilo-ambrosio It looks like the wrong class is being passed as a template parameter. I wanted to fix this myself but it's not obvious to me where this happens. This is apparently the template involved:

`/vlingo-xoom/src/main/resources/codegen/JournalProvider.ftl`

**Comment by danilo-ambrosio** [comment]
@VaughnVernon 
Thanks for your help.
Indeed, there is a wrong parameter in regard to `JournalProvider`. I can handle that ASAP.

**Comment by VaughnVernon** [comment]
Hey @danilo-ambrosio Do you know if this was fixed? This must be in 1.4.0.

**Comment by danilo-ambrosio** [comment]
@VaughnVernon 
This was fixed on `starter` master branch. 

@flaxel 
Please download the update `starter` binaries and let me know if everything is fine now. Note that I've also temporarily enabled the new user interface version which will be the definitive `starter` interface soon.

**Comment by flaxel** [comment]
Sorry for the late reply. I had problems with Windows yesterday. I tried it today and it worked for me. +1
