### ISSUE TITLE
Inform user with successfully started log message after every component fully loaded even http handler.

### ISSUE THREAD

**Issue by hurelhuyag** [vlingo/vlingo-xoom-starter#45]
Currently project has no such message. Maybe users check application status with browser. But in automation it is not good. We need a log message to detect if application is started successfully or not.

For example I check tomcat startup health with this message "INFO: Server startup in 53209 ms". If I receive this message, It means application is running.

**Comment by VaughnVernon** [comment]
We generally leave that to the service/application to log because we don't actually know when everything is running. The starter current generates this:

```
public class XoomInitializer implements XoomInitializationAware {
  ...
  public static void main(final String[] args) throws Exception {
    System.out.println("=========================");
    System.out.println("service: petclinic.");
    System.out.println("=========================");
    instance = new XoomInitializer(args);
  }
  ...
}
```

Are you looking for more? We could move the log output to after the `XoomInitializer` is instantiated, but due to the async nature of XOOM we don't know when "everything" is running.

**Comment by VaughnVernon** [comment]
Sorry, I still don't understand.

Do you mean that when the `vlingo-xoom-starter` process is fully running and the UI loads in the browser that we should log something that says that the starter UI is running in the browser?

**Comment by hurelhuyag** [comment]
@VaughnVernon We should log something when `vlingo-xoom-starter` is ready to handle requests.

**Comment by VaughnVernon** [comment]
It's there already: 

https://github.com/vlingo/vlingo-http/blob/7752c8ca867d70c00e07498c41221ce9a71bde44/src/main/java/io/vlingo/http/resource/ServerActor.java#L126

**Comment by hurelhuyag** [comment]
@VaughnVernon Thank you. This is working as expected.
