### ISSUE TITLE
[UI] Aggregate Dialog API URI Path Confusion

### ISSUE THREAD

**Issue by VaughnVernon** [vlingo/vlingo-xoom-starter#48]
We are trying too hard to enforce the use of an `.../{id}/...` in the URI path that it's causing problems. Literally I am prevented from editing the URI prior to the `/{id}/` text. This causes big problems in the API design. The following should work:

```
Root path:
/
Path:
animalTypes              POST ...
Path:
/animalTypes/{id}/name    PATCH ...
...
```

Instead I am forced to have the `/{id}/` as the first segment of the URI and I can't override it. This means that the above `PATCH` example would have to be like this, which is wrong:

```
Root path:
/
Path:
/ animalTypes    POST ...  
Path:
/{id}/animalTypes/name     PATCH ...
...
```

Thus if I want to design the API to be anywhere near to correct, I am forced to rework the design and also use a trailing `/` where there should not be one (or it is not required nor does it make sense):

```
Root path:
/animalTypes   <=== move the prefix here
Path:
/     POST ...   <=== requires trailing / such as: /animalTypes/    because the Path text cannot be empty
Path:
/{id}/name     PATCH ...  <===== this now works, but at the expense of the POST URL
...
```

Can we just allow the URI to be entered by the user as they wish and scan for the required `/{id}` as existing anywhere in the URL for non-`POST` APIs? If the `/{id}` doesn't exist, the it is an error. Please don't try to enforce a specific location for the `/{id}` pattern.

**Comment by Florian-Schoenherr** [comment]
@VaughnVernon Earlier on, `/animalTypes` would have been the rootPath, in this case.

Now it might be best to just provide regex validation for `/{id}/`
OR even better, have a field which let's the user _choose_ path-params and enforce them with regex, so if you want:
```
get("/animalTypes/{id}")
            .param(java.lang.String.class)
            .body(group.artifact.infrastructure.AnimalTypesData.class)
            .handle(this::define),
```
it would be:

```
Path-Parameters v         <-- Select-Field
   id ✔️ 
   name
   isReptile

/animalTypes/{id} GET   <-- Validation enforces `{id}`
```

**Comment by VaughnVernon** [comment]
Fixed.
