### ISSUE TITLE
Consider adding Maven Wrapper to the distribution bundle

### ISSUE THREAD

**Issue by yuri-sergiichuk** [vlingo/vlingo-xoom-starter#6]
While it is stated in the requirements that Maven is required, it may be some extra pain for users to install one with wider adoption of wrappers approach.

It'd be great to have [Maven Wrapper](https://github.com/takari/maven-wrapper) in the `xoom-starter` bundle as well as in the generated project.

**Comment by VaughnVernon** [comment]
@yuri-sergiichuk Please see this PR and review if you have time.

https://github.com/vlingo/vlingo-xoom-starter/pull/7

**Comment by yuri-sergiichuk** [comment]
Closed with #7 and #11.
